# Copyright 2019 Mujtaba Idrees
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.5'

networks:
    avalon-network:
        external:
            name: avalon-network
services:
  openvino-scone-worker-1:
    container_name: openvino-scone-worker-1
    image: scone-openvino-dev
    build:
      context: .
      dockerfile: Dockerfile-sconecurated-openvino
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - ./output:/output
    command: |
      ash -c "ash script.sh openvino-scone-worker-1"
    networks:
         - avalon-network

  openvino-scone-worker-2:
    container_name: openvino-scone-worker-2
    image: scone-openvino-dev
    build:
      context: .
      dockerfile: Dockerfile-sconecurated-openvino
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - ./output:/output
    command: |
      ash -c "ash script.sh openvino-scone-worker-2"
    networks:
         - avalon-network

  openvino-scone-worker-3:
    container_name: openvino-scone-worker-3
    image: scone-openvino-dev
    build:
      context: .
      dockerfile: Dockerfile-sconecurated-openvino
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - ./output:/output
    command: |
      ash -c "ash script.sh openvino-scone-worker-3"
    networks:
         - avalon-network

  openvino-scone-worker-4:
    container_name: openvino-scone-worker-4
    image: scone-openvino-dev
    build:
      context: .
      dockerfile: Dockerfile-sconecurated-openvino
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - ./output:/output
    command: |
      ash -c "ash script.sh openvino-scone-worker-4"
    networks:
         - avalon-network

  openvino-scone-worker-5:
    container_name: openvino-scone-worker-5
    image: scone-openvino-dev
    build:
      context: .
      dockerfile: Dockerfile-sconecurated-openvino
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - ./output:/output
    command: |
      ash -c "ash script.sh openvino-scone-worker-5"
    networks:
         - avalon-network