version: '3.2'

networks:
    avalon-network:
        external:
            name: $AVALON_NETWORK
services:
    redis:
        container_name: scone-redis
        image: registry.scontain.com:5050/sconecuratedimages/apps:redis-6-alpine-scone4
        command: sh -c "sleep 5; SCONE_LOG=7 SCONE_LAS_ADDR=las SCONE_CAS_ADDR=$SCONE_CAS_ADDR SCONE_CONFIG_ID=$REDIS_SESSION/redis redis-server"
        devices:
         - "$DEVICE"
#        depends_on:
#         - las
        ports:
         - "6379"
        environment:
         - SCONE_VERSION=1
        networks:
         - avalon-network
    python:
        container_name: $FLASK_APP_ALIAS
        image: "$IMAGE"
        devices:
         - "$DEVICE"
        command: sh -c "sleep 5; SCONE_LOG=7 SCONE_LAS_ADDR=las SCONE_CAS_ADDR=$SCONE_CAS_ADDR SCONE_CONFIG_ID=$FLASK_SESSION/flask_restapi python3"
#        depends_on:
#         - las
        privileged: true
        ports:
         - "4996"
        links:
         - redis
        networks:
         - avalon-network
